### ISSUE TITLE
Add ability to render to files

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad-pack#109]
When using Pack in CI/CD, it would be great to be able to render to a file.

Something like `nomad-pack render <PACK> --to=./path/to/dir` maybe?

**Comment by tgross** [comment]
@groggemans yeah it looks like that was noted in https://github.com/hashicorp/nomad-pack/issues/163. Not being able to do stdout/stderror redirection is going to be problematic for a bunch of workflows we'd certainly love to enable.
