### ISSUE TITLE
enhancement: respect XDG standards 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad-pack#115]
`nomad-pack` is effectively hard-coded to create `$HOME/.nomad`

Ideally it should follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which suggests the default directory for this cache might belong in `$XDG_CACHE_HOME` (`$HOME/.cache/.nomad` if unset).

**Comment by angrycub** [comment]
Closed by #172
