### ISSUE TITLE
Nomad-Pack support for namespaces

### ISSUE THREAD

**Issue by pandom** [hashicorp/nomad-pack#120]
Nomad Pack support for Namespaces generally. If you take advantage of a namespace variable in a `nomad-pack` you will no longer be able to manage it after deployment and will need to leverage the `nomad` agent CLI.

** reproduction steps**

`nomad -dev` and `consul agent -dev`

Here I can deploy a pack to a specific namespace `test`
```
nomad-pack run nomad_autoscaler --var namespace=test
  Evaluation ID: edb3fc84-9944-5f9a-1fe2-695071e6eadf
  Job 'nomad_autoscaler' in pack deployment 'nomad_autoscaler@latest' registered successfully
Pack successfully deployed. Use --name=nomad_autoscaler@latest to manage this this deployed instance with run, plan,
or destroy
```

The job runs in the namespace `test`
```
nomad job status --namespace=test
ID                Type     Priority  Status   Submit Date
nomad_autoscaler  service  50        running  2021-10-19T10:00:46+11:00
```

`nomad-pack` has no awareness of the namespace job, only what is in default.

```
 nomad-pack status
   PACK NAME  | REGISTRY NAME
--------------+----------------
  hello_world | default
  ```

**Proposed Solution**

Allow the ability to append `--namespace=<namespace_name>` to `nomad-pack` to accomodate life cycling packs deployed into namespace.

**Comment by jrasell** [comment]
Hi @pandom and thanks for identifying and raising this issue. This is certainly something we should handle and I believe the proposed solution is the right approach and probably should extend to plan, run, and destroy in some manner.

**Comment by mikenomitch** [comment]
Will be closed by this one! - https://github.com/hashicorp/nomad-pack/pull/230
