### ISSUE TITLE
`nomad-pack` does not support basic auth in `NOMAD_ADDR` env var

### ISSUE THREAD

**Issue by Davasny** [hashicorp/nomad-pack#153]
Using username and password included in `NOMAD_ADDR`:

```bash
$ export NOMAD_ADDR=https://user:pass@example.com/
$ nomad-pack run hello_world
! Failed To Parse Job Specification

        Error:   401 Unauthorized
        Type:    client.GenericOpenAPIError
        Context:
                 - Template Name: hello_world/templates/hello_world.nomad.tpl
                 - Registry Name: default
                 - Pack Name: hello_world
                 - Pack Ref: latest
                 - Deployment Name: hello_world@latest
$ nomad status
ID           Type     Priority  Status   Submit Date
hello_world  service  50        running  2021-10-24T13:04:06+02:00
traefik      service  50        running  2021-07-14T20:36:18+02:00
```

As you can see, `nomad` supports this way of authorization but `nomad-pack` doesn't

**Note**: details in `NOMAD_ADDR` were redacted due to security reasons

**Comment by Davasny** [comment]
Hi @jrasell, do you have any update on this?

**Comment by DerekStrickland** [comment]
Hi @Davasny.  This actually looks like a problem in the upstream [Nomad OpenAPI project](https://github.com/hashicorp/nomad-openapi/issues/65).   Thanks for the reminder. I'll take a look at it and see if we can't get it working and then get pack updated.
