### ISSUE TITLE
some errors returned are obtuse

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad-pack#164]
the newly added jenkins pack contains an error and when i try to run it the error returned by nomad-pack is less than useful.  I had to render the pack and manually and run the job, to get presented with some reasonable feedback from the system.

to reproduce.

> packs ❯ pwd 
> nomad-pack-community-registry/packs
packs ❯ nomad-pack run jenkins -f jenkins/vars.nomad
! Failed To Parse Job Specification

	Error:   400 Bad Request
	Type:    client.GenericOpenAPIError
	Context:
	         - Template Name: jenkins/templates/jenkins.nomad.tpl
	         - Registry Name: dev
	         - Pack Name: jenkins
	         - Pack Ref: dev
	         - Deployment Name: jenkins
> packs ❯ nomad-pack render jenkins -f jenkins/vars.nomad

safe the output to a file (see #163 for my bug report about not being able to pass directly to file) and run it using the nomad cli

> packs ❯ nomad run jenkins.nomad              
> Error getting job struct: Failed to parse using HCL 2. Use the HCL 1 parser with `nomad run -hcl1`, or address the following issues:
> jenkins.nomad:61,7-13: Unsupported argument; An argument named "config" is not expected here. Did you mean to define a block of type "config"?

**Comment by jrasell** [comment]
Hi @attachmentgenie and thanks for raising this issue.

@DerekStrickland is this something that can be improved on the OpenAPI side of things?

**Comment by DerekStrickland** [comment]
@jrasell Probably, if the CLI gave a better error message, thought I suspect this will be a framework change to support custom error messages that Nomad returns (in the backlog already).  I'll take this for a spin, and see if it's the same issue, and if so what I can do to provide a better DX.

**Comment by tgross** [comment]
I ran into this same issue while reviewing https://github.com/hashicorp/nomad-pack-community-registry/pull/47#discussion_r743881497. It looks like we're just swallowing the Nomad CLI errors that are going to stderr?

**Comment by mikenomitch** [comment]
Adding this to the tech_preview_2 milestone as its a pretty big gap in the pack writing/testing workflow.
