### ISSUE TITLE
Nomad-pack plan has an exit code of 1

### ISSUE THREAD

**Issue by azdim** [hashicorp/nomad-pack#224]
Successful nomad-pack plan returns an exit code of 1. This issue was discovered when using a CI/CD pipeline within GitHub actions, although a `continue-on-error: true` prevents the pipeline from failing it is not a viable long term solution.

```
❯ nomadpack plan . -f ./nomad_vars.hcl
Job: "mark"
Task Group: "app" (1 create/destroy update, 1 in-place update)
  Task: "server"

» Scheduler dry-run:
- All tasks successfully allocated.
Plan succeeded

root in template_nomad_repo/packs/hello_world on  init 🏎💨  v1.1.5default took 2s
❯ echo $?
1
```

**Comment by resmo** [comment]
I don't see an issue if plan uses an other exit code then 0 if something changes, this is quite useful to detect changes.

But we should think about using a code other then 1.

Probably worth thinking is to make it configurable e.g. `nomad job plan --exit-code-on-change=2` with a default of `1` for backwards compatibility
