### ISSUE TITLE
Question: Does deployed packs auto update when a pack is changed?

### ISSUE THREAD

**Issue by devantler** [hashicorp/nomad-pack#245]
Hey, I want to use nomad-pack to provide me with a GitOps workflow where changes to packs in my repository are reflected on my cluster. Is this possible with nomad-pack yet? Or do I need to run `nomad-pack run` whenever I make a change to a pack?

**Comment by mikenomitch** [comment]
Hey @devantler, you'll need to have some CI flow that re-runs `nomad-pack run` in response to the changes.

If you had nomad-pack in a Github Action (or CI job with your tool of choice), then pulled down the latest changes and re-ran `run` that shoudl work. Hopefully wouldn't be a quick setup! 🤞

**Comment by devantler** [comment]
@mikenomitch I do not think this is easy to do with a bare metal setup. Is there any plans on making a guide for creating a GitOps workflow with GitHub actions and different setups? Or maybe even plans of making a service that can be deployed in a nomad cluster to watch a repo for nomad pack updates and pull changes?

Besides some general enhancements to nomad pack, i thing this is one of the things that will make pack registries really easy to use.
