### ISSUE TITLE
client: set client region and namespace based on jobspec

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-pack#266]
The `nomad job run` command sets the [region and namespace](https://github.com/hashicorp/nomad/blob/1d8d1ab81953f1cc3a2acfcab33aa0101a4bb478/command/job_run.go#L245-L253) of the Nomad client to that contained within the jobsepc. The nomad-pack run command currently does not do this which requires users to set both a variable to set the jobspec region parameter, and export the `NOMAD_REGION` env var to set the client correctly.

nomad-pack should mimic the Nomad behaviour, so users can use both tools in the same manner without problems.

**Comment by pkazmierczak** [comment]
Resolved by https://github.com/hashicorp/nomad-pack/pull/366
