### ISSUE TITLE
Update Nomad Pack Nomad API Libraries to 1.3.X+

### ISSUE THREAD

**Issue by robloxrob** [hashicorp/nomad-pack#270]
I was working on Nomad Pack deployments and found that they couldn't submit jobs correctly with `max_client_disconnect`. From what I can tell this is related to the Nomad libraries that are used (I am using tech preview 2). Can you please pull in the PR #249 (once they update it to 1.3.1 😄 ) as I believe that will solve it. Thank you @mikenomitch !

**Comment by robloxrob** [comment]
I updated the dependencies and tested with a local build, it worked as expected with correctly setting the MaxClientDisconnect.

**Comment by DerekStrickland** [comment]
Thanks @robloxrob.  I'll take a look at this.
