### ISSUE TITLE
Formatting HCL

### ISSUE THREAD

**Issue by banmanh482** [hashicorp/nomad-pack#274]
I got this problem when run `make dev`: 

```
go install gotest.tools/gotestsum@latest
--> Formatting HCL
xargs: hclfmt: No such file or directory
make: *** [GNUmakefile:65: hclfmt] Error 127
```
How can solve this problem, can someone help me

**Comment by angrycub** [comment]
Hey @banmanh482, it looks like you don't have the `hclfmt` command installed or that it's installed to a directory not in your path.  Typically the make process installs that tool automatically. Could you confirm that `hclfmt` is in your path? If not, go usually instals in your `${GOPATH}/bin` folder.

**Comment by lgfa29** [comment]
`make bootstrap` will install the required tooling, but I forgot to update the contributing guides to mention this step 😅 

https://github.com/hashicorp/nomad-pack/pull/275 will correct this.

**Comment by OTorrado** [comment]
I m having the same error and i already did the two option that you give me.

**Comment by angrycub** [comment]
If you are getting the same error, then the `hclfmt` binary is not available in your path. What operating system are you using to try to build?  As lgfa29 mentioned, you can obtain it by using `make bootstrap` or you can run

```
go install github.com/hashicorp/hcl/v2/cmd/hclfmt@d0c4fa8b0bbc2e4eeccd1ed2a32c2089ed8c5cf1
```

which will install the version used at `main`.  Once installed, you should be able to run `hclfmt -h` and get usage text.  If this doesn't work, then there is something misconfigured with your Go environment, such that items compiled and installed using `go install` are not in your path.  I have had similar problems when using Go version managers that I hadn't configured quite correctly.

**Comment by mikenomitch** [comment]
I think this is resolved, so closing
