### ISSUE TITLE
Nomad Pack homebrew installed binary not honouring $HOME/.nomad/packs path

### ISSUE THREAD

**Issue by lhaig** [hashicorp/nomad-pack#280]
Environment:
Macbook Pro M1
OSX 12.5
Terminal Iterm2
`nomad-pack version`
`Nomad Pack v0.0.1-techpreview2`
What is expected:
After running `nomad-pack registry list` I expect to find the local registry cache to be in `$HOME/.nomad/packs`

It can instead be found in `/Users/USER/Library/Caches/nomad/packs`

**Comment by tgross** [comment]
@lhaig I wouldn't expect it to be there following https://github.com/hashicorp/nomad-pack/pull/172. Is that still documented somewhere?

**Comment by lhaig** [comment]
I have seen it here.
https://learn.hashicorp.com/tutorials/nomad/nomad-pack-intro?in=nomad/nomad-pack
and this file just mentions ./.nomad
https://github.com/hashicorp/nomad-pack/blob/main/docs/detailed-usage.md

**Comment by lhaig** [comment]
What is better wording? Happy to update the learn guide.

**Comment by tgross** [comment]
Maybe something like:

> The first time you run registry list, Nomad Pack will add a `.nomad/packs` directory to your desktop user's cache directory (`$XDG_CACHE_DIR` on Linux, `~/Library/Caches` on macOS, `%AppData%` on Windows, etc.). This will store information about available packs.
