### ISSUE TITLE
make dev fails when GOPATH includes multiple paths

### ISSUE THREAD

**Issue by gucio** [hashicorp/nomad-pack#319]
The make dev fails on https://github.com/hashicorp/nomad-pack/blob/main/GNUmakefile#L76 if GOPATH includes multiple paths like "/path/1:/path/2". 

Such GOPATH is valid as described here: https://go.googlesource.com/vscode-go/+/refs/heads/dev.go2go/docs/gopath.md

The error I see:
```
==> Building nomad-pack...
cp: /Users/gucio/dev:/usr/local/go/bin/nomad-pack: No such file or directory
make: *** [dev] Error 1
```

caused by `GOPATH=${HOME}/dev:/usr/local/go`. Also note that `go install` behaves correctly.

**Comment by angrycub** [comment]
I definitely see where that would cause it to go wrong. We definitely need to split the path at least. 

According to the current [How to Write Go](https://go.dev/doc/code) page 

> The install directory is controlled by the GOPATH and GOBIN environment variables. If GOBIN is set, binaries are installed to that directory. If GOPATH is set, binaries are installed to the bin subdirectory of the first directory in the GOPATH list. Otherwise, binaries are installed to the bin subdirectory of the default GOPATH ($HOME/go or %USERPROFILE%\go).

Let's see if we can't adopt that pattern for the makefile too. The reason it removes the original before it writes a new one is to make macOS happy. An alternative we could consider is sniffing for macOS and only doing the remove/copy dance then.
