### ISSUE TITLE
tests: fix cli tests

### ISSUE THREAD

**Issue by isabeldepapel** [hashicorp/nomad-pack#32]
A couple issues when running the entire cli test file:
+ We're running into what looks like issues with concurrency and the job names, which is nomad_example in all our tests (either hardcoded or default name)
+ We need to fix the ui output--it looks like maybe we want to switch to something thread safe like the mockUI in nomad or maybe even suppress the output since it's very verbose

**Comment by mikenomitch** [comment]
Closing this out as there have been some improvements to this in the background!

For new CLI test improvements I'd open a new issu.
