### ISSUE TITLE
nomad hcl functions can't be used in a nomad pack

### ISSUE THREAD

**Issue by avandierast** [hashicorp/nomad-pack#320]
Hello :)

Since two weeks, I have a problem with the rendering of my packs with the nightly build.
I get the following error :
```
Error: failed to format the template ... , At : Unknown token: 11:25 IDENT <function_name>
```

It seems to be caused by this PR (https://github.com/hashicorp/nomad-pack/issues/301) that added formatting to nomad job files.
And it seems to fail when we use any nomad hcl functions: https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/functions

When we add --no-format, everything works.

The following job definition (in a pack) can't be rendered:
```
job "test" {
    group "test" {
        task "test" {
            driver = "docker"

            config {
                image = "busybox"
            }

            env {
                VALUE=max(10,20)
            }
        }
    }
}
```

**Comment by slonopotamus** [comment]
I'm observing the same issue with HCL2 variables:

```hcl
variable "bla" {
  type        = string
  default     = ""
}

job "test" {
}
```

Gives:
```
Error:   failed to format the template templates/test.nomad.tpl, At 2:17: Unknown token: 2:17 IDENT string
```

**Comment by slonopotamus** [comment]
See https://github.com/hashicorp/nomad-pack/pull/420 for a fix.
