### ISSUE TITLE
feature: Support --var-file in json format

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad-pack#347]
--var-file supports only hcl format. But most tools (Jenkins) do not have hcl format support, but easily have json generators. Please support var-file in json format.

**Comment by pschichtel** [comment]
I've written this jq expression to circumvent the limitation:

```jq
def tohcl(n; root): if type == "object" then (
    if root then (
        to_entries | map((.key | tojson) + " = " + (.value | tohcl(n; false))) | join("\n\n")
    ) else (
        "{\n" + ("    " * (n + 1)) + (to_entries | map(.key + " = " + (.value | tohcl(n + 1; false))) | join("\n" + ("    " * (n + 1)))) + "\n" + ("    " * n) + "}"
    ) end
) else (
    if type == "array" then (
        "[\n" + ("    " * (n + 1)) + (map(tohcl(n + 1; false)) | join(",\n" + ("    " * (n + 1)))) + "\n" + ("    " * n) + "]"
    ) else (
        tojson
    ) end
) end;

. | tohcl(0; true)
```

It's pretty much a json to hcl converter, at least as much as I need it.

**Comment by Kamilcuk** [comment]
Hi, this is still a stopper for us for using nomad-pack. I would want to integrate nomad-pack with our Jenkins pipelines, and jenkins/groovy can generate JSON files, but I can't then load them to nomad-pack. We currently use a short python script that loads the json and calls jinja2. We could also call nomad-pack with command line arguments, but then escaping (because Jenkins) is once again an issue.

**Comment by angrycub** [comment]
As of Nomad Pack v0.1.0, the -var-file flag supports variable files having a `.json` extension.  It came in as a part of the new parser enhancements.
