### ISSUE TITLE
nomad-pack generate pack should land in packs directory

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad-pack#355]
When trying to generate a pack in the top level of a registry using the following command that pack doesnt land in the packs directory, which has annoyed/confused me a couple of times. I mean there is little effort to move it to the right location after creation but i tend to forget it.

`nomad-pack generate packs/prometheus_blackbox_exporter `

The process errors out when generating the pack directly into the sub-directory

```
nomad-pack-registry ❯ nomad-pack generate pack packs/prometheus_blackbox_exporter                                                                                                                  main
Creating "packs/prometheus_blackbox_exporter" Pack in "."...
! Failed To Generate Pack

        Error:   create pack error: createPackFile.create packs/prometheus_blackbox_exporter/templates/packs/prometheus_blackbox_exporter.nomad.tpl: open
packs/prometheus_blackbox_exporter/templates/packs/prometheus_blackbox_exporter.nomad.tpl: no such file or directory
        Type:    *fmt.wrapError
        Context: 
                 - Pack Name: packs/prometheus_blackbox_exporter
                 - Output Path: .
```

would it make sense to have the original command create the pack directly into the packs sub-directory?

**Comment by pkazmierczak** [comment]
Hi @attachmentgenie, `generate pack` supports a `-o` flag:

```
  -o, --to-dir=<string> (default "."
        Path to write generated pack to. Defaults to ..
```

Would that solve your issue?

**Comment by attachmentgenie** [comment]
learn something new everyday, @pkazmierczak yeah that will work.
