### ISSUE TITLE
No path to region

### ISSUE THREAD

**Issue by pschichtel** [hashicorp/nomad-pack#374]
Hi, I've not actually found helpful information and I feel like it might actually be a bug in nomad-pack:

I have a rather simple pack for an internal application. It contains just one template. When I render it and deploy it with `nomad job plan` and `nomad job run`, then everything works fine as I'd expect it.

However, if I use `nomad-pack plan` or `nomad-pack run` directly, then I'm always presented with this output:

```
! Failed Job Conflict Validation

        Error:   No path to region
        Type:    *v1.APIError
        Context: 
                 - Template Name: kotlin_demo/templates/kotlin_demo.nomad.tpl
```

Nomad client version: `v1.5.6` (from `nomad version`)
Nomad server version: `1.5.6` (from `nomad server members`)
Nomad-pack version: `v0.0.1-techpreview.4 (50d84d0)` (from `nomad-pack version`

**Comment by attachmentgenie** [comment]
you seem to be hitting #266, good news is a fix will be released soon.

In the mean time you have to do `export NOMAD_REGION=$YOURREGIONNAME nomad-pack run`

**Comment by pschichtel** [comment]
I looked at #266 and the related PR #366 and it seems this assumes I configured a region in my job spec, but I haven't. I guess my deployment relies on the server default, which nomad-pack doesn't use.

**Comment by pschichtel** [comment]
The [documentation](https://developer.hashicorp.com/nomad/docs/commands) says "`NOMAD_REGION` - The region of the Nomad server to forward commands to. Defaults to the Agent's local region", I guess that default is simply missing?

**Comment by attachmentgenie** [comment]
This is one of those times where nomad-pack currently is different from the vanilla nomad cli. Hence this confusing behaviour which has bitten me more than once. But as i said the nomad team has fixed this in #366, coming to a nightly/release near you soon

**Comment by pschichtel** [comment]
Ah I just realized that your `nightly` tag isn't actually moved nightly. I'll build from master then.

**Comment by pschichtel** [comment]
Yep, I can confirm it's working on main branch.

**Comment by pschichtel** [comment]
I've setup two AUR package for nomad pack: [nomad-pack-git](https://aur.archlinux.org/packages/nomad-pack-git) (builds main) and [nomad-pack-nightly](https://aur.archlinux.org/packages/nomad-pack-nightly) (builds the nightly tag), so I'm covered for now :)
