### ISSUE TITLE
Consider changing `generate var-file` to `render var-file`

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad-pack#378]
Caveat: I am new enough to `nomad-pack` that this may be a convention that oughtn't be changed, so please feel free to ignore this request.

Since the default behaviour of `nomad-pack generate var-file` is console output, and only by using the `--to-file` flag would you generate a new file, should we consider moving its command space to `nomad-pack render var-file` ?

The current behaviour seems notably different than `nomad-pack generate pack`, which does generate local file and directory changes.

**Comment by mikenomitch** [comment]
Yeah I think it's more findable in generate too.

What if we change the default behavior to output a file (like the other generates)? IMO that might be more intuitive.

Default name <packname>-vars.hcl, or something like that?

**Comment by pkazmierczak** [comment]
After discussing with @angrycub and @mikenomitch we decided to keep the current behavior, i.e., stdout by default and optionally write to file. The reasoning is that we expect most people to use `generate var-file` inside CI, piping the output into other tools, editors, etc. I'm gonna close this issue for now and the corresponding PR, and we can always revisit in the future.
