### ISSUE TITLE
${attr.consul.version} semver >= 1.7.0

### ISSUE THREAD

**Issue by AAverin** [hashicorp/nomad-pack#388]
Running basic nomad-pack setup and trying to execute `prometheus` from `default` repository, I get an error 

```
* Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
```

I though Nomad has it's own Service Discover and Consul isn't required?

To reproduce: `nomad-pack plan prometheus`, run on MacOS M1
with .tfvars set to
```
constraints = [
    {
      attribute = "$${attr.kernel.name}",
      value     = "darwin",
      operator  = "",
    }
]
```

**Comment by AAverin** [comment]
Can be related to https://github.com/hashicorp/waypoint/issues/3376

**Comment by AAverin** [comment]
The issue seems to be resolved after installing Consul and running `consul agent -dev -bind 0.0.0.0 -log-level INFO`
Although the question still stands, do we need Consul?

**Comment by AAverin** [comment]
Looks like the community pack I was using had `connect` enabled, so Consul was necessary there.

**Comment by aliegrsp** [comment]
* Constraint "${attr.consul.version} semver >= 1.8.0". (Nomad 1.7.5 & Consul 1.18.0).
* I have this problem and my version of consul is 1.18.0.
* I have followed the tutorial.
* https://developer.hashicorp.com/nomad/tutorials/integrate-consul/consul-acl
