### ISSUE TITLE
github.com/hashicorp/nomad-pack/terminal.(*nonInteractiveUI).ErrorWithContext

### ISSUE THREAD

**Issue by Thadir** [hashicorp/nomad-pack#396]
Version NomadPack:  Nomad Pack v0.0.1-techpreview.4 (50d84d0)

I run nomad-pack as a CLI agent for Jenkins to publish standard builds to I get a very interesting panic from my server:

13:45:34  + nomad-pack version
13:45:34  Nomad Pack v0.0.1-techpreview.4 (50d84d0)
13:45:34  
13:45:34  + nomad-pack registry add mycrop ssh://gittea.dev.benelux.intra.corp:2222/nomad_pack_templates.git
13:45:34  debug: %!s(MISSING)
13:45:34  go-getter URL is ssh://gittea.dev.benelux.intra.corp:2222/nomad_pack_templates.git
13:45:35  debug: %!s(MISSING)
13:45:35  Registry successfully cloned at /home/jenkins/agent/.cache/nomad/packs/nomad-pack-tmp
13:45:35  debug: %!s(MISSING)
13:45:35  Processing pack entries at /home/jenkins/agent/.cache/nomad/packs/nomad-pack-tmp
13:45:35  debug: %!s(MISSING)
13:45:35  found pack entry argos_client
13:45:35  debug: %!s(MISSING)
13:45:35  Processing pack argos_client@latest
13:45:35  ! Error Checking Pack Directory
13:45:35    temp directory deleted
13:45:35  panic: runtime error: invalid memory address or nil pointer dereference
13:45:35  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfbe181]
13:45:35  
13:45:35  goroutine 1 [running]:
13:45:35  github.com/hashicorp/nomad-pack/terminal.(*nonInteractiveUI).ErrorWithContext(0x0?, {0x0, 0x0}, {0x1310f88, 0x1d}, {0xc000122300, 0x5, 0xc0005bf7e0?})
13:45:35  	github.com/hashicorp/nomad-pack/terminal/noninteractive.go:213 +0xa1
13:45:35  github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).processPackEntry(0xc0000b4720, 0xc0005bf9a8, {0x1638bb8?, 0xc0005f9d80?})
13:45:35  	github.com/hashicorp/nomad-pack/internal/pkg/cache/add.go:174 +0x50a
13:45:35  github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).addFromURI(0xc0000b4720, 0xc0005bfcd8)
13:45:35  	github.com/hashicorp/nomad-pack/internal/pkg/cache/add.go:112 +0x451
13:45:35  github.com/hashicorp/nomad-pack/internal/pkg/cache.(*Cache).Add(0xc0000b4720, 0xc0005bfcd8)
13:45:35  	github.com/hashicorp/nomad-pack/internal/pkg/cache/add.go:52 +0xab7
13:45:35  github.com/hashicorp/nomad-pack/internal/cli.(*RegistryAddCommand).Run(0xc000034190, {0xc0000340d0?, 0x2, 0x2})
13:45:35  	github.com/hashicorp/nomad-pack/internal/cli/registry_add.go:62 +0x771
13:45:35  github.com/mitchellh/cli.(*CLI).Run(0xc000126280)
13:45:35  	github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
13:45:35  github.com/hashicorp/nomad-pack/internal/cli.Main({0xc0000340a0?, 0x5, 0x5})
13:45:35  	github.com/hashicorp/nomad-pack/internal/cli/main.go:96 +0x2b0
13:45:35  main.main()
13:45:35  	github.com/hashicorp/nomad-pack/main.go:15 +0x77

This recently happened when I rebuild a image with the latest nichtly.

**Comment by angrycub** [comment]
Thank you for your report; we will investigate this issue. However, as mentioned in the nightly release notes, we don't recommend running nightlies in any production pipelines, as there are no stability guarantees until we make an official release.

**Comment by Thadir** [comment]
Agreed, on that with thet last nichtly it got fixed.
