### ISSUE TITLE
getting undefined variable when using as part of url path

### ISSUE THREAD

**Issue by doorman02** [hashicorp/nomad-pack#412]
### Nomad version
Output from `v1.5.6`

### Operating system and Environment details
Linux

### Issue
Hi I am trying to use a variable inside my .nomad file like this

```
variable "versionPrefix" {
  type    = string
  default = substr("[[.env.myversion]]", 1, 10)
}

job "testing" {
  meta {
MyTestingPath = "https://testing.io?version%3A[[ get $.var $versionPrefix ]]"
}
```

but I am getting the error:
`undefined variable "$versionPrefix"`

#### Expected Result
MyTestingPath  should contain the path with the value from the variable

#### Actual Result
`undefined variable "$versionPrefix"`

**Comment by slonopotamus** [comment]
I believe the correct syntax is `${var.versionPrefix}` instead of `$.var $versionPrefix`. And no, it has nothing to do with Nomad Pack.

**Comment by angrycub** [comment]
Thanks for the assist @slonopotamus! Since this issue looks related to conflating Pack variables with Nomad variables, I'm going to mark it closed. If I misunderstood, I encourage you to open a new issue.
