### ISSUE TITLE
Node pools not working via nomad-pack

### ISSUE THREAD

**Issue by albertoperdomo2** [hashicorp/nomad-pack#424]
Since [Nomad 1.6](https://www.hashicorp.com/blog/nomad-1-6-adds-node-pools-ux-updates-and-more) there are node pools supported by nomad, which are a new way to determine which client nodes are eligible to receive workloads. To use node pools, first add a node_pool value to a Nomad client in its agent configuration file. Clients are added to the node pool called “default” unless otherwise specified in the client config. 

With `nomad-pack`, the render of the template containing the **node_pool** variable seems to work fine, but when I run it, it is uploaded to Nomad without that variable and therefore it is included in the default pool. However, using the Nomad cli to deploy the same job works, so I believe it's something related to **nomad-pack**.

For instance, something like this:
```
job "[[ template "job_name" . ]]" {
  namespace = "foo"
  datacenters = [ "[[ .my.environment ]]" ]
  type = "service"
  node_pool = "[[ .my.node_pool ]]"

  group "app" {
    count = [[ .my.count ]]

    network {
      port "http" {
        to = 3000
      }
    }

    service {
      name = "[[ template "service_name" . ]]"
      port = "http"

      check {
        type = "http"
        port = "http"
        protocol = "http"
        path = "/health_check"
        interval = "5s"
        timeout = "2s"
      }

    task "server" {
      driver = "docker"

      [[ template "resources" . ]]
      
      env {
        AWS_REGION="[[ .my.aws_region ]]"
      }

      config {
        image = "my_image:[[ .my.image_tag ]]"
        ports = ["http"]
        image_pull_timeout = "30m"
      }
    }
  }
  }
}
```

would render as:
```
job "my_job_name" {
  namespace   = "foo"
  datacenters = ["DC1"]
  type        = "service"
  node_pool   = "non_default"

  group "app" {
    count = 1

    network {
      port "http" {
        to = 3000
      }
    }

    service {
      name = "my_job-nomad"
      port = "http"

      check {
        type     = "http"
        port     = "http"
        protocol = "http"
        path     = "/health_check"
        interval = "5s"
        timeout  = "2s"
      }

      task "server" {
        driver = "docker"

        resources {
          cpu    = 3000
          memory = 5000

          device "nvidia/gpu" {
            count = 1
          }
        }

        env {
          AWS_REGION = "my_region"
        }

        config {
          image              = "my_image:latest"
          ports              = ["http"]
          image_pull_timeout = "30m"
        }
      }
    }
  }
}
```

But, as said, `node_pool` in Nomad is set to `default`.

**Comment by bernardoVale** [comment]
@albertoperdomo2 I had the same problem, but I can confirm that using the latest code from the main branch works.

**Comment by attachmentgenie** [comment]
you ll need nomad-pack 0.1.0 to be able to use node_pool in your jobs
