### ISSUE TITLE
git ssh address error in install doc

### ISSUE THREAD

**Issue by kevinpan45** [hashicorp/nomad-pack#431]
git ssh address in doc is `git@github.com/hashicorp/nomad-pack`
address in github is `git@github.com:hashicorp/nomad-pack.git`

doc link https://developer.hashicorp.com/nomad/tutorials/nomad-pack/nomad-pack-intro#installing-nomad-pack

**Comment by angrycub** [comment]
Thanks for that catch @kevinpan45.  I have filed a PR on the internal tutorial repo to update that URL.
