### ISSUE TITLE
0.1.0 release doesn't provide binaries

### ISSUE THREAD

**Issue by slonopotamus** [hashicorp/nomad-pack#470]
Basically, subj. It would be very convenient to be able to download binaries from [release page](https://github.com/hashicorp/nomad-pack/releases/tag/v0.1.0). Currently, nomad-pack users need to build it from source.

**Comment by jrasell** [comment]
Hi @slonopotamus; in-line with other HashiCorp product builds nomad-pack pre-compiled binaries are available from the HashiCorp releases page: https://releases.hashicorp.com/nomad-pack/

**Comment by slonopotamus** [comment]
Okay, though that page is impossible to find. Both this repository README and https://developer.hashicorp.com/nomad/tutorials/nomad-pack/nomad-pack-intro talk about building from source.
