### ISSUE TITLE
enhancement:  Move version specifier to separate flag and rebrand as revision

### ISSUE THREAD

**Issue by DerekStrickland** [hashicorp/nomad-pack#81]
The @version specifier in the `registry add --from` flag is cumbersome to users and leads to a lot of error-prone string parsing. We should make this it's own flag. We should also rename it to `revision` as that is what it more accurately represents - the git revision.  We'll have to think about how this works or doesn't work with filesystem-based registries.

**Comment by jrasell** [comment]
@DerekStrickland can this issue now be closed?
